import { MigrationInterface, QueryRunner } from "typeorm";

export class Basicdb1714993308639 implements MigrationInterface {
    name = 'Basicdb1714993308639'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "leave_request" DROP CONSTRAINT "FK_f766e108254ec5f667628700b5f"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_646b91cc56d9fd9760973b4980d"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_5c8d26dee2b23a5a654f1a27606"`);
        await queryRunner.query(`CREATE TABLE "clockin" ("id" SERIAL NOT NULL, "clock_in" TIMESTAMP NOT NULL DEFAULT now(), "clock_out" TIMESTAMP, "employee_id" integer, CONSTRAINT "PK_6ec0c11fccf421c0ac1798e90e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hr_letters" ("id" SERIAL NOT NULL, "letter_subject" character varying(1024) NOT NULL, "letter_content" character varying(1024) NOT NULL, "letter_time" TIMESTAMP NOT NULL DEFAULT now(), "employee_id" integer, CONSTRAINT "PK_99a50a9f62f37c3a9581106f9ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permission" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_19a94c31d4960ded0dcd0397759" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a7155eafd75ddba5a701336" ON "role_permission" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3a3ba47b7ca00fd23be4ebd6c" ON "role_permission" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "employee_n_buddies" ("employee_id" integer NOT NULL, "buddies_id" integer NOT NULL, CONSTRAINT "PK_ce6808bbec49655e898f80d21f1" PRIMARY KEY ("employee_id", "buddies_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41e0ab448dc118d9cf73b6e24b" ON "employee_n_buddies" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fa865679a6393c3b8e5c14eec" ON "employee_n_buddies" ("buddies_id") `);
        await queryRunner.query(`CREATE TABLE "employee_n_skill" ("employee_id" integer NOT NULL, "skill_id" integer NOT NULL, CONSTRAINT "PK_ba20df38be52de7fba5c99e00e8" PRIMARY KEY ("employee_id", "skill_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eac235ceaee666224ce14fe2f6" ON "employee_n_skill" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7ca3321c08af5dc80369fd218" ON "employee_n_skill" ("skill_id") `);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "permissionName"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "permissionDescription"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "roleName"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "roleDescription"`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "employeeId"`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "employeeUsername"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "roleId"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "departmentId"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "skill_id"`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "permission_name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "permission_description" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" ADD "role_name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" ADD "role_description" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "status" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "employee_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "first_name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "last_name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "salary" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "date_of_joining" date NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "role_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "department_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "branch_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "company_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project" ADD "end_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task" ADD "lastName" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task" ADD "end_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "from_date"`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "from_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "to_date"`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "to_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "PK_8e3e7d82a105202ae6bbda01828"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "UQ_389fe2fe09430efb8eabc4e1b6e" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD CONSTRAINT "FK_f457a5663e14c8aa27ce95a8a6a" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "clockin" ADD CONSTRAINT "FK_fa7f04c2b2112822dd7da29c45a" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_letters" ADD CONSTRAINT "FK_2302daebe9c328288a67a6dba20" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_1c105b756816efbdeae09a9ab65" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_d62835db8c0aec1d18a5a927549" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_380241ef3c0ea0a87b9411f37ff" FOREIGN KEY ("branch_id") REFERENCES "branch"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_3f25598a5f106392263f58a2eb2" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee_n_buddies" ADD CONSTRAINT "FK_41e0ab448dc118d9cf73b6e24b1" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee_n_buddies" ADD CONSTRAINT "FK_9fa865679a6393c3b8e5c14eec7" FOREIGN KEY ("buddies_id") REFERENCES "buddies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee_n_skill" ADD CONSTRAINT "FK_eac235ceaee666224ce14fe2f69" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee_n_skill" ADD CONSTRAINT "FK_b7ca3321c08af5dc80369fd218b" FOREIGN KEY ("skill_id") REFERENCES "skill"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "employee_n_skill" DROP CONSTRAINT "FK_b7ca3321c08af5dc80369fd218b"`);
        await queryRunner.query(`ALTER TABLE "employee_n_skill" DROP CONSTRAINT "FK_eac235ceaee666224ce14fe2f69"`);
        await queryRunner.query(`ALTER TABLE "employee_n_buddies" DROP CONSTRAINT "FK_9fa865679a6393c3b8e5c14eec7"`);
        await queryRunner.query(`ALTER TABLE "employee_n_buddies" DROP CONSTRAINT "FK_41e0ab448dc118d9cf73b6e24b1"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_3f25598a5f106392263f58a2eb2"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_380241ef3c0ea0a87b9411f37ff"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_d62835db8c0aec1d18a5a927549"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_1c105b756816efbdeae09a9ab65"`);
        await queryRunner.query(`ALTER TABLE "hr_letters" DROP CONSTRAINT "FK_2302daebe9c328288a67a6dba20"`);
        await queryRunner.query(`ALTER TABLE "clockin" DROP CONSTRAINT "FK_fa7f04c2b2112822dd7da29c45a"`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP CONSTRAINT "FK_f457a5663e14c8aa27ce95a8a6a"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "UQ_389fe2fe09430efb8eabc4e1b6e"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "PK_8e3e7d82a105202ae6bbda01828" PRIMARY KEY ("id", "username")`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "to_date"`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "to_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "from_date"`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "from_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "date_of_joining"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "salary"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "employee_id"`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "role_description"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "role_name"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "permission_description"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "permission_name"`);
        await queryRunner.query(`ALTER TABLE "task" ADD "skill_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "companyId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "branchId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "departmentId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "roleId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "lastName" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "firstName" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "employeeUsername" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD "employeeId" integer`);
        await queryRunner.query(`ALTER TABLE "role" ADD "roleDescription" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" ADD "roleName" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "permissionDescription" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "permissionName" character varying(64) NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7ca3321c08af5dc80369fd218"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eac235ceaee666224ce14fe2f6"`);
        await queryRunner.query(`DROP TABLE "employee_n_skill"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fa865679a6393c3b8e5c14eec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41e0ab448dc118d9cf73b6e24b"`);
        await queryRunner.query(`DROP TABLE "employee_n_buddies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3a3ba47b7ca00fd23be4ebd6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0a7155eafd75ddba5a701336"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP TABLE "hr_letters"`);
        await queryRunner.query(`DROP TABLE "clockin"`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_5c8d26dee2b23a5a654f1a27606" FOREIGN KEY ("skill_id") REFERENCES "skill"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_646b91cc56d9fd9760973b4980d" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD CONSTRAINT "FK_f766e108254ec5f667628700b5f" FOREIGN KEY ("employeeId", "employeeUsername") REFERENCES "employee"("id","username") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
